### ISSUE TITLE
unable to install lifecycle

### ISSUE THREAD

**Issue by anon94041** [r-lib/lifecycle#103]
I'm trying to create a parameterized report in RMarkdown; my session info is below.  I pull down Knit with parameters, and it says:
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘lifecycle’
I say: install.packages("lifecycle") and it enters a loop that only ends when I give up and press "cancel" -- see below.  Any ideas?  Thanks for any help.

Error in install.packages : Updating loaded packages
> install.packages("lifecycle")
Error in install.packages : Updating loaded packages

Restarting R session...

Loading required package: sp
> install.packages("lifecycle")
Error in install.packages : Updating loaded packages

Restarting R session...

Loading required package: sp
> install.packages("lifecycle")
Error in install.packages : Updating loaded packages

(it only stops looping when I say "cancel")

My R version info:
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          0.3                         
year           2020                        
month          10                          
day            10                          
svn rev        79318                       
language       R                           
version.string R version 4.0.3 (2020-10-10)
nickname       Bunny-Wunnies Freak Out

**Comment by gaborcsardi** [comment]
Seems like you are loading some packages from your `.Rprofile`, and lifecycle will be loaded as well, and then RStudio warns you about updating a loaded package. You can answer "No" to RStudio's question, lifecycle has no compiled code, so you can update it even if it is loaded.

Alternatively, do load any packages from the `.Rprofile`.

You can also try to use pak, which deals with updating loaded packages better. Make sure you use the dev version of pak: https://github.com/r-lib/pak#installation

**Comment by anon94041** [comment]
Thank you, that's helpful...  I haven't touched .Rprofile, I'm just using whatever .Rprofile came along with the default R and RStudio installations.  As you suggested, I responded "No" to RStudio's question about restarting R, but then it has trouble with rlang instead (see below).  I'm a pretty vanilla user of R and RStudio, and haven't had trouble installing packages before, so am not very knowledgeable about what to do.  Thanks very much for any advice.  (I replaced the path with my user name with <path> in the below, but let me note my user name only contains a-z characters and a period, no apostrophes or anything interesting.)

My session now:

> install.packages("lifecycle")
Error in install.packages : Updating loaded packages
> install.packages("lifecycle")
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
also installing the dependency ‘rlang’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/rlang_0.4.10.zip'
Content type 'application/zip' length 1196950 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/lifecycle_1.0.0.zip'
Content type 'application/zip' length 111193 bytes (108 KB)
downloaded 108 KB

package ‘rlang’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  cannot remove prior installation of package ‘rlang’
Warning in install.packages :
  problem copying <path>R\R-4.0.3\library\00LOCK\rlang\libs\x64\rlang.dll to <path>R\R-4.0.3\library\rlang\libs\x64\rlang.dll: Permission denied
Warning in install.packages :
  restored ‘rlang’
package ‘lifecycle’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	<path>AppData\Local\Temp\1\Rtmp8WhprT\downloaded_packages
> knit_with_parameters('~/scratch.Rmd')
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘rlang’ 0.4.9 is already loaded, but >= 0.4.10 is required

**Comment by gaborcsardi** [comment]
If you haven't changed `.Rprofile`, then there is something else that loads rlang and the other packages. Maybe there are some data objects in your project that trigger the loading of sf, etc.
So you can try to create a new project, close the other RStudio windows if you have any, and try the installation in the new project.

Alternatively, give pak a try, it is pretty easy, install pak first, and then use it to install lifecycle, etc.

```r
install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
pak::pkg_install("lifecycle")
```

pak will interact with you about the loaded packages and it can unload them before the installation.

**Comment by anon94041** [comment]
Your instructions for pak worked.  Thank you very much for your help and for walking me through this.
