### ISSUE TITLE
Cannot install lifecycle via RStudio or R GUI

### ISSUE THREAD

**Issue by amethystinia** [r-lib/lifecycle#104]
I have been trying to install lifecycle because apparently car will not run without it. However, every time I try - and I have tried the repository and package modes - I get the following error:

```
* installing *source* package 'lifecycle' ...
** package 'lifecycle' successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: unexpected string constant in:
"suppressPackageStartupMessages(.getRequiredPackages(quietly = TRUE))
tools:::makeLazyLoading("lifecycle", '"
Execution halted
ERROR: lazy loading failed for package 'lifecycle'
* removing 'C:/Program Files/R/R-4.0.4/library/lifecycle'
Warning in install.packages :
  installation of package ‘C:/Users/Misha'ari/Downloads/lifecycle_1.0.0.tar.gz’ had non-zero exit status
```
I'm running:

R version 4.0.4 (2021-02-15) -- "Lost Library Book"
Platform: x86_64-w64-mingw32/x64 (64-bit)

I'm not well versed enough in programming or R to know how to fix this so I'm hoping someone else can help! Please and thank you!

**Comment by lionel-** [comment]
@gaborcsardi @jeroen Have you ever seen this sort of install error on Windows? There is also #103.

**Comment by gaborcsardi** [comment]
The output you show is a bit weird, there is currently a binary package for lifecycle 0.2.0 and a source package for lifecycle 1.0.0 on CRAN, and R normally messages about this. Can you please show the command you run and the full output? Thanks.

**Comment by jeroen** [comment]
I think this has to do with diacritics in your username: `C:/Users/Misha'ari/Downloads`. I think you would need to report this to base R. Can you test if the same problem appears with R 4.0.3 or if it is new with R 4.0.4?

**Comment by gaborcsardi** [comment]
I am fairly sure that this has been broken at least since the staged installation. Maybe it has never worked, actually.

**Comment by kalibera** [comment]
My guess is Jeroen is right, the output has a surprising apostrophe and the user name has an apostrophe. Of course if you find where exactly R could handle quotes better (with a patch), we'll fix that, but it would likely break somewhere else then - certainly a login name only consisting of ASCII letters would be a good choice.

**Comment by gaborcsardi** [comment]
Unfortunately one cannot always choose their login name. You often get a company laptop where your login name is your real name, and if that contains an apostrophe, or a Unicode character, etc. then using R will be not very pleasant for you.

Maybe this particular instance could be fixed, the string is assembled here:
https://github.com/wch/r-source/blob/436ac6a39a072512aa2def9a9d0c2ab234d897a2/src/library/tools/R/install.R#L1578
but the real culprit is `quote_path()`, which just creates a single-quoted string, so having a single quote in any of the paths will fail:
https://github.com/wch/r-source/blob/436ac6a39a072512aa2def9a9d0c2ab234d897a2/src/library/tools/R/install.R#L150-L156

**Comment by kalibera** [comment]
That handling of single quotes is working, but it is R-devel code (patch from Kevin Ushey), R 4.0.4 does not handle them.
You can reproduce by trying to install any package into a directory containing an apostrophe, e.g.
```
install.packages("codetools", lib='/tmp/a\'b')
```

**Comment by gaborcsardi** [comment]
Great, so this is fixed already then.

**Comment by lionel-** [comment]
Thanks for the discussion everyone!

@amethystinia As Jeroen pointed out you can work around with this for now:

```r
 install.packages('lifecycle', type = 'binary')
```
