### ISSUE TITLE
Soft-deprecated badge in lifecycle package leads to an empty section

### ISSUE THREAD

**Issue by dpprdan** [r-lib/lifecycle#105]
This is basically the same as #101, now for "Soft-deprecated".

I.e. `badge("soft-deprecated")` creates https://lifecycle.r-lib.org/articles/stages.html#soft-deprecated, but the `#soft-deprecated` anchor is not on https://lifecycle.r-lib.org/articles/stages.html

``` r
library(lifecycle)
badge("soft-deprecated")
#> [1] "\\ifelse{html}{\\href{https://lifecycle.r-lib.org/articles/stages.html#soft-deprecated}{\\figure{lifecycle-soft-deprecated.svg}{options: alt='[Soft-deprecated]'}}}{\\strong{[Soft-deprecated]}}"
```

**Comment by lionel-** [comment]
You should now use `badge("deprecated")`. We still support `"soft-deprecated"` for compatibility, but this is now undocumented.
