### ISSUE TITLE
Soft-deprecated stage superseded or not?

### ISSUE THREAD

**Issue by dpprdan** [r-lib/lifecycle#106]
The `badge()` documentation says that the "soft-deprecated" stage is superseded:

https://github.com/r-lib/lifecycle/blob/6c98892fbefe240127b43b44d45b8bedacb2b5fc/R/badge.R#L43-L44

But the "stages" and "communicate" make it sound that it is still a valid, albeit special, stage:

https://github.com/r-lib/lifecycle/blob/6c98892fbefe240127b43b44d45b8bedacb2b5fc/vignettes/stages.Rmd#L64-L69

https://github.com/r-lib/lifecycle/blob/6c98892fbefe240127b43b44d45b8bedacb2b5fc/vignettes/communicate.Rmd#L161-L166

Is this a mistake in the `badge()` documentation?

**Comment by hadley** [comment]
The soft-deprecated badge is superseded; it's now just a subclass of deprecated.

**Comment by dpprdan** [comment]
What I meant to say is: The docs are not consistent in whether the soft-deprecated state is superseded or not, IMO. Or is the difference between the soft-deprecated badge (superseded) and the soft-deprecated stage/`deprecated_soft()` function (not-superseded)? If it is, then _that's_ not clear.

**Comment by lionel-** [comment]
Maybe we can just remove the mention of "superseded" in `?badge`:

> `"questioning"`, `"maturing"`, `"soft-deprecated"`,
>  "`defunct`", and `"retired"` are supported for backwards compatibility.

**Comment by dpprdan** [comment]
As a ({lifecycle}) user, the main thing I'd like to know is whether a particular stage is still recommended or whether I should switch to another stage at the earliest convenience to a better alternative. Descriptions like "superseded" (and also "backwards compatibility") convey that there exists such a better (simpler, clearer, actionable) alternative. The `"questioning"`, `"maturing"`, and `"retired"` stages fit this description. 

From my reading of the vignettes, `"soft-deprecated"` and `"defunct"` seem to be a different bag, namely "use them sparingly for 'particularly important functions'". There aren't better alternatives, they are just for special cases.

So how about:

> `"soft-deprecated"` and `"defunct"` are subclasses of `"deprecated"` and should only be used for particularly important functions. 
> Superseded stages `"questioning"`, `"maturing"`, and `"retired"` are supported for backwards compatibility.

**Comment by lionel-** [comment]
The thing is that to keep things simple, we no longer use soft-deprecated and defunct badges. We only use a "deprecated" badge.

We could also just remove mention of these badges supported for backwards compatibility in the documentation since they are a distraction.

**Comment by hadley** [comment]
Yeah, I think that's probably the best approach.
