### ISSUE TITLE
Make the badges accessible to screenreader

### ISSUE THREAD

**Issue by jennybc** [r-lib/lifecycle#117]
It would be nice if the lifecycle badge SVGs included the stage in `aria-label` or similar.

As the maintainer of usethis and, therefore, the one-who-adds-lots-of-badges, I'm making similar requests in various places.

Gabor already did it (a while ago) in the badges provided by METACRAN:
https://github.com/metacran/metacranweb/commit/8287a21e6dc2bc50a2d8a7b5a5a56904ae1d04ff

shields.io badges already are accessible FWIW.

I'm not sure how the `.svg`s here are actually made but presumably it's not too hard to do this.

``` r
library(tidyverse)

show_aria_label <- function(badge) {
  badge %>%
    xml2::read_xml() %>%
    xml2::as_list() %>%
    pluck("svg") %>%
    attributes() %>%
    pluck("aria-label")
}
```

<img src="https://www.r-pkg.org/badges/version/usethis">

``` r
show_aria_label("https://www.r-pkg.org/badges/version/usethis")
#> [1] "CRAN 2.1.5"
```

<img src="https://www.r-pkg.org/badges/last-release/usethis">

``` r
show_aria_label("https://www.r-pkg.org/badges/last-release/usethis")
#> [1] "CRAN 2021-12-09"
```

<img src="https://cranlogs.r-pkg.org/badges/usethis">

``` r
show_aria_label("https://cranlogs.r-pkg.org/badges/usethis")
#> [1] "CRAN downloads 270K/month"
```

<img src="https://img.shields.io/github/workflow/status/r-lib/usethis/R-CMD-check?label=R-CMD-check">

``` r
show_aria_label("https://img.shields.io/github/workflow/status/r-lib/usethis/R-CMD-check?label=R-CMD-check")
#> [1] "R-CMD-check: passing"
```

<img src="https://img.shields.io/badge/my__label-my__message-orange">

``` r
show_aria_label("https://img.shields.io/badge/my__label-my__message-orange")
#> [1] "my_label: my_message"
```

<img src="https://raw.githubusercontent.com/r-lib/lifecycle/main/man/figures/lifecycle-experimental.svg">

``` r
show_aria_label("https://raw.githubusercontent.com/r-lib/lifecycle/main/man/figures/lifecycle-experimental.svg")
#> NULL
```

<sup>Created on 2021-12-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by hadley** [comment]
@batpigandme is this something you'd be interested in doing?

**Comment by batpigandme** [comment]
@hadley sure thing

**Comment by batpigandme** [comment]
Question/point of clarification:

@jennybc, the way that the lifecycle badges are generated **in usethis** ([badge.R#L93-L113](https://github.com/r-lib/usethis/blob/b0318bf7cadd25797ae97301893923933207c5ca/R/badge.R#L93-L113)), they _do_ have aria-labels, right? From https://github.com/r-lib/usethis/blob/b0318bf7cadd25797ae97301893923933207c5ca/R/badge.R#L101
```r
  src <- glue("https://img.shields.io/badge/lifecycle-{stage}-{colour}.svg")
```

you'd get, e.g.https://img.shields.io/badge/lifecycle-stable-brightgreen.svg for stable.

``` r
library(tidyverse)

show_aria_label <- function(badge) {
  badge %>%
    xml2::read_xml() %>%
    xml2::as_list() %>%
    pluck("svg") %>%
    attributes() %>%
    pluck("aria-label")
}

show_aria_label("https://img.shields.io/badge/lifecycle-stable-brightgreen.svg")
#> [1] "lifecycle: stable"
```

<sup>Created on 2022-08-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jennybc** [comment]
Yes shields.io badges do have aria labels. This issue is about the properties of static svgs we provide.

**Comment by batpigandme** [comment]
10-4. I replaced the ones in the lifecycle package itself (https://github.com/batpigandme/lifecycle/tree/aria-labels), but I've not been able to suss out where they're actually built in the lifecycle (I messaged lionel for clarification). So, it's a WIP right now.

**Comment by hadley** [comment]
I think each package will need to re-run `use_lifecycle()` in order to update their copy of the lifecycle badges.

**Comment by batpigandme** [comment]
Yeah, that's what it looked like to me—that the badges themselves aren't actually constructed in lifecycle locally. Do you still want the PR to fix the aria-labels for the badges for lifecycle?

**Comment by jennybc** [comment]
> I think each package will need to re-run use_lifecycle() in order to update their copy of the lifecycle badges.

This seems like a good candidate for upkeep checklist item.
