### ISSUE TITLE
scoped_* -> local_*

### ISSUE THREAD

**Issue by hadley** [r-lib/lifecycle#12]
For compatibility with withr

**Comment by lionel-** [comment]
Should rlang switch as well?

**Comment by lionel-** [comment]
Maybe we should just unexport these helpers since we now have a simple option:

```r
scoped_options(lifecycle_verbosity = "warning")
```

**Comment by hadley** [comment]
Yes, rlang should change, and I'm fine with relying on withr/rlang instead of providing a bunch of functions here.
