### ISSUE TITLE
Minimum R version for installation

### ISSUE THREAD

**Issue by jrhadams** [r-lib/lifecycle#121]
I had a quick question regarding your package. Looking at your package description, your minimum R version listed is currently >=3.3, however, I'm having issues with an 3.6 installation in a docker environment. 

```bash
user@Desktop:~$ docker run -ti --rm rocker/r-ver:3.6.0 R

R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages('lifecycle')
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning message:
package ‘lifecycle’ is not available (for R version 3.6.0)
```
I've also attempted installing the package directly from your git repo with devtools and this was also unsuccessful. When I attempt a later installation like 4.1.0, however, there where no issues with installation. 

```bash
user@Desktop:~$ docker run -ti --rm rocker/r-ver:4.1.0 R

R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages('lifecycle')
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
also installing the dependencies ‘glue’, ‘rlang’

trying URL 'https://packagemanager.rstudio.com/cran/__linux__/focal/2021-08-09/src/contrib/glue_1.4.2.tar.gz'
Content type 'binary/octet-stream' length 144559 bytes (141 KB)
==================================================
downloaded 141 KB

trying URL 'https://packagemanager.rstudio.com/cran/__linux__/focal/2021-08-09/src/contrib/rlang_0.4.11.tar.gz'
Content type 'binary/octet-stream' length 1395145 bytes (1.3 MB)
==================================================
downloaded 1.3 MB

trying URL 'https://packagemanager.rstudio.com/cran/__linux__/focal/2021-08-09/src/contrib/lifecycle_1.0.0.tar.gz'
Content type 'binary/octet-stream' length 93556 bytes (91 KB)
==================================================
downloaded 91 KB

* installing *binary* package ‘glue’ ...
* DONE (glue)
* installing *binary* package ‘rlang’ ...
* DONE (rlang)
* installing *binary* package ‘lifecycle’ ...
* DONE (lifecycle)

The downloaded source packages are in
        ‘/tmp/Rtmp8oPdTf/downloaded_packages’

```

Is there something that I am missing?

Thanks in advance.

**Comment by lionel-** [comment]
In the latter case, the packages are installed from binary via RSPM. In the former case, I don't know. It only issues a warning (but I know that sometimes `install.packages()` warns instead of erroring, confusingly). is the package still installed, perhaps from source?

There are two things you can investigate, why you can't install from binary, and why you can't install from source. Regarding binaries, first check what CRAN repository are you using. If the repo is from CRAN itself, it won't have any binary for Linux. If it's RSPM, make sure it has binaries for the R version you're using. The best thing would be to be able to compile from source.

Also perhaps try `remotes::install_url(TAR_GZ_URL_FOR_SOURCE_PACKAGE_FROM_THE_CRAN_PAGE)`.

This is more of a user question than a dev issue, so a user forum or service support would be better able to help you. Unfortunately I'm not really knowledgeable about administration issues.

**Comment by lionel-** [comment]
Closing but you're welcome to keep discussing here of course, if you have further questions.

**Comment by jrhadams** [comment]
Yikes, I played around with pointing to a specific repo explicitly and I was able to install with no problem. 

```r
> remotes::install_version("lifecycle",version="1.0.1",repos="https://cloud.r-project.org")
```

Apologies for taking your time on this. I really appreciate your thoughtful response.
