### ISSUE TITLE
Lifecycle images in html render of help are broken

### ISSUE THREAD

**Issue by jzadra** [r-lib/lifecycle#123]
All of the images for lifecycle in my package are broken.  They used to work and stopped some time ago, not sure exactly when.

I have re-run `usethis::use_lifecycle()` and ensured that the svg files are in man/figures.

Here is an example of one rendered help document, documenation code above the function in the .R file,  and the  .Rd file:

![image](https://user-images.githubusercontent.com/25590353/178567138-43d174f0-f259-4144-be1b-0eefcec134b6.png)

```
#' Check whether a file has unsaved changes
#' @description
#' `r lifecycle::badge('experimental')`
#' Checks for an open file with unsaved changes. Currently used internally by qa()
#' @export
```

```
% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/utils.R
\name{is_unsaved}
\alias{is_unsaved}
\title{Check whether a file has unsaved changes}
\usage{
is_unsaved(path, warn_only = F)
}
\description{
\ifelse{html}{\href{https://lifecycle.r-lib.org/articles/stages.html#experimental}{\figure{lifecycle-experimental.svg}{options: alt='[Experimental]'}}}{\strong{[Experimental]}}
Checks for an open file with unsaved changes. Currently used internally by qa()
}
```

**Comment by hadley** [comment]
Are you previewing the development version of the documentation? There's a known issue with RStudio (fixed in the next release) that prevents images from working there.
