### ISSUE TITLE
Capture deprecated_warn() conditions and resignal?

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-lib/lifecycle#140]
Hello. Is there a mechanism available for capturing `lifecycle_stage` conditions signaled by `deprecated_warn()` and friends, such that one can re-signal them later as if they were not intercepted?

For example, consider:

```r
> lifecycle::deprecate_warn("1.0.0", "foo()", "bar()", always = TRUE)
Warning message:
`foo()` was deprecated in <NA> 1.0.0.
Please use `bar()` instead.
```

If we attempt to capture condition this, we get:

```r
> cond <- tryCatch(lifecycle::deprecate_warn("1.0.0", "foo()", "bar()", always = TRUE), condition = identity)
> str(cond)
List of 8
 $ message       : 'glue' chr "foo() is deprecated"
 $ stage         : chr "deprecated"
 $ package       : chr "lifecycle"
 $ function_nm   : chr "foo"
 $ argument      : NULL
 $ reason        : NULL
 $ call          : NULL
 $ use_cli_format: logi TRUE
 - attr(*, "class")= chr [1:2] "lifecycle_stage" "condition"
```

This condition is not a `warning` condition, so using `signalCondition(cond)` will not generate the intended warning.

I understand that **lifecycle** uses another internal layer of condition handlers;

https://github.com/r-lib/lifecycle/blob/0a6860af815500c51697780464af19c0f389d2f6/R/deprecate.R#L252-L256

that comes into play. (I haven't tracked down the full call stack in the code, but some tracing/debugging led me to this piece of code.)

Is there a way to capture-and-resignal what `deprecate_warn()` and friends produces?

PS. My use case is to capture them in `future::future()`, possibly being resolved in another R process, and then relay them in the main R session as if they were produced there.

**Comment by lionel-** [comment]
I think that's a case where you'd use `withCallingHandlers()`? If you do handle the condition, jump non-locally. If you don't, return normally to let the condition signal pursue its course.

You can use `rlang::try_fetch()` to make this easier: return normally to handle the condition, return `rlang::zap()` to decline handling.

**Comment by lionel-** [comment]
Ah no actually the first comment was relevant. If you really want to propagate non critical conditions (i.e. that do not inherit from error), then use `withCallingHandlers()`, collect and save the conditions somewhere, then resignal them.

**Comment by HenrikBengtsson** [comment]
Thank you. Sorry, I dropped the ball on this one.

I only used `tryCatch()` to simplified my example. I do indeed use `
withCallingHandlers()` in **future**, where this problem stems from.

I'll try to reply with more details later.

**Comment by HenrikBengtsson** [comment]
Closing in favor of #147, which appears to be the essence of my original problem.
