### ISSUE TITLE
Use inline R code for badges

### ISSUE THREAD

**Issue by wlandau** [r-lib/lifecycle#17]
Would you help me understand why `usethis::use_lifecycle()` adds `lifecycle` to Imports rather than Suggests?

```r
> library(usethis)
> use_lifecycle()
✔ Setting active project to '/home/landau/projects/drake'
✔ Adding 'lifecycle' to Imports field in DESCRIPTION
...
```

I am new to `lifecycle`, and I am happy to see that tidyverse lifecycle badges have become more widely available.

**Comment by lionel-** [comment]
It's only needed for deprecated functions really. You might want to wait before we publish the blog post though, there are last minute UI discussions going on ;). Also we'll change some of the badge colours.

**Comment by lionel-** [comment]
Sratch that, `lifecycle::badge()` must be available at runtime so the HTML documentation can be rendered. So that's `Imports`, not `Suggests`. It's a lightweight dependency though. Maybe I'll create a base R `compat-badge.R` file for those who only want the badges.

**Comment by wlandau** [comment]
Thanks for explaining, @lionel-.

The badges show up correctly when I copy the output of `cat(badge())` and paste it at the end of the `@title`. You have made that part so easy that I am likely to skip the Rd macro to avoid incurring another package dependency, however light.

**Comment by wlandau** [comment]
Hmm... maybe not. The code creates long lines, so the macros are actually really handy.

**Comment by lionel-** [comment]
I think if you just copy badge.R in your package, and make the macro call `mypkg:::badge.R()`, this should work without the dependency.

**Comment by wlandau** [comment]
Sounds reasonable, thanks. I will go with that.

**Comment by hadley** [comment]
In the next version of roxygen you'll be able to do :

```R
#' `r lifecycle::badge("deprecated")`
```

That will run `badge()` at document time, so lifecycle won't need to be in imports and you don't need some other compat layer. I've changed the title to reflect the work that'll need to be done when the next version of roxygen2 is out.

**Comment by jennybc** [comment]
@lionel- When you do this, will you also determine if `usethis::use_lifecycle()` needs an associated update?

https://github.com/r-lib/usethis/blob/9b462b1918bb1e089d3160724131dfa6746fb1fa/R/lifecycle.R#L21

**Comment by krlmlr** [comment]
For updating existing code with GNU sed:

```sh
sed -r -i 's/\\lifecycle[{](.*)[}]/`r lifecycle::badge("\1")`/' R/*
```

**Comment by lionel-** [comment]
Thanks Kirill! This variant may also be useful with the old lifecycle compat files:

```sh
gsed -r -i 's/\\Sexpr\[results=rd, stage=render\][{]rlang:::lifecycle\((.*)\)[}]/`r lifecycle::badge(\1)`/' R/*
```

**Comment by lionel-** [comment]
Looks like we'll need https://github.com/r-lib/roxygen2/issues/1115 solved first.

**Comment by krlmlr** [comment]
The great thing about develop-time dependencies: you can install locally from a branch :upside_down_face:
