### ISSUE TITLE
identify which functions are deprecated, soft deprecated, ...

### ISSUE THREAD

**Issue by romainfrancois** [r-lib/lifecycle#2]
so that we can have data about what a package considers deprecated, etc ...

**Comment by lionel-** [comment]
What do you have in mind? If that's about generating metadata, I think roxygen tags might be best.

**Comment by romainfrancois** [comment]
It's not clear to me. on a high level I guess this would help when a package developer wants to make sure they don't use anything deprecated. 

The system in place helps identifying cases as you go, and hopefully people will take the hints, but what if I want to specifically tackle deprecation of things I depend on.

**Comment by lionel-** [comment]
you set `lifecycle_errors()` and then run your tests? Assuming good coverage.

**Comment by hadley** [comment]
I think this can be closed now?
