### ISSUE TITLE
Message for when default values change?

### ISSUE THREAD

**Issue by joethorley** [r-lib/lifecycle#24]
It might be useful to provide a message once per session for default values that have changed and were not explicitly set by the user so that they can decide whether to go with the old or new behaviour.

**Comment by nteetor** [comment]
I second being able to deprecate an argument value in general.

**Comment by hadley** [comment]
@joethorley  Changing a default value wouldn't usually be considered an interface change, so is out of scope for this package.

@nteetor You can already deprecate an argument.

**Comment by nteetor** [comment]
Hello @hadley, I am aware of and use the argument deprecation feature.

> I second being able to deprecate an argument value in general.

I was focusing on an argument's values. For example, a function changes possible value `"regular"` to `"medium"`. As far as I know, this not supported. You mention not supporting changes to default values, but I am looking to change possible values by deprecating one or more values. I am hopeful this falls within the package scope. If so I can work on a PR. I can also transition to a fresh issue if useful.

**Comment by hadley** [comment]
I think that's too specialised for this package. You can just manually `warn()`.

**Comment by nteetor** [comment]
Okay, understood. I'll brew up a local solution.
