### ISSUE TITLE
"Strict" mode when accessing a retired function?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/lifecycle#29]
Can we treat retired functions like soft-deprecated ones, but keep silent by default and only enable messages if a retired function is used?

**Comment by hadley** [comment]
Our current policy is to treat superseded functions equivalently to stable functions; i.e. they need to go through a deprecation cycle before they can be used, so I don't _think_ this is needed.

**Comment by krlmlr** [comment]
I might care about superseded functions if I want to proactively clean up API usage. Let's revisit when this need arises somewhere.
