### ISSUE TITLE
"retired" is not documented

### ISSUE THREAD

**Issue by yutannihilation** [r-lib/lifecycle#34]
https://lifecycle.r-lib.org/reference/badge.html says the argument of `badge()` can be

> one of: "experimental", "maturing", "stable", "questioning", "archived", "soft-deprecated", "deprecated", "defunct".

But, I found "retired" is used in https://dplyr.tidyverse.org/dev/reference/top_n.html.

As a side question, what's the relationship between the stages lifecycle package provides and the ones on https://www.tidyverse.org/lifecycle/? I know the former is for functions and arguments while the latter is for packages, so they can be different. But, I also don't feel these are two different things.

(Sorry if this is not the right place to ask here...)

**Comment by lionel-** [comment]
We are now going to use "superseded" instead of "retired". The package lifecycle stages and function lifecycle stages mostly correspond, except that we don't typically deprecate packages.

**Comment by yutannihilation** [comment]
Thanks, makes sense now!
