### ISSUE TITLE
CRAN check failure after adding lifecycle

### ISSUE THREAD

**Issue by jpritikin** [r-lib/lifecycle#39]
CRAN check of [OpenMx](https://github.com/OpenMx/OpenMx/commit/212925df1ac85a177957c28ad58f853514f68270) started failing with,

```
Package has help file(s) containing install/render-stage \Sexpr{} expressions but no prebuilt PDF manual.
```

This problem disappeared after [I revert the addition of lifecycle](https://github.com/OpenMx/OpenMx/commit/957a4c1fe60e4f88389194f51299a21c8a0533db).

Any idea about the root cause? I'd like to use lifecycle, but I can't.

**Comment by lionel-** [comment]
Removing `--no-manual` from your CMD check flags should fix it.

**Comment by lionel-** [comment]
You can also ignore the NOTE in your CI system, CRAN will build the manual to check it in any case.

**Comment by jpritikin** [comment]
Eh, but this resulted in a rejected CRAN submission,

```
Thanks, we see:

  Package has help file(s) containing install/render-stage \Sexpr{}
expressions but no prebuilt PDF manual.

Please fix and resubmit.

Best,
Uwe Ligges
```

**Comment by lionel-** [comment]
I haven't encountered this case yet, not sure what's going on.

Maybe you have to build without `--no-manual` before sending for release? I'm generally using `devtools::release()` which might do it automatically.

**Comment by jpritikin** [comment]
I've never used `--no-manual` when I build a tarball. I just do `R CMD build .`

**Comment by lionel-** [comment]
Maybe @gaborcsardi knows more about this sort of issues with Sexpr.

**Comment by jpritikin** [comment]
As a minimum, the error message could be made more specific and understandable.

**Comment by gaborcsardi** [comment]
@jpritikin where is your tarball?

**Comment by jpritikin** [comment]
[Here](https://vipbg.vcu.edu/vipbg/OpenMx2/software//travis/tmp/OpenMx_2.16.0-27.tar.gz)

**Comment by gaborcsardi** [comment]
Sry, I mean, a full check on a CI or by CRAN.

**Comment by jpritikin** [comment]
> Sry, I mean, a full check on a CI or by CRAN.

Can you explain more fully? The version with lifecycle never got onto CRAN (see rejection above). What do you mean by "CI"? If you mean _continuous integration_ then I never did a `R CMD check --as-cran` on Travis. However, I did this on my local machine and obtained the same vague complaint,

```
Package has help file(s) containing install/render-stage \Sexpr{}
expressions but no prebuilt PDF manual.
```
There are no further details about the context. I can run it again and post a tarball of the full check results, if that would help. Let me know what you need.

Thanks.

**Comment by gaborcsardi** [comment]
Failed CRAN submissions should be here: https://win-builder.r-project.org/incoming_pretest/ and there is a bunch for OpenMx, although I don't know which one failed for lifecycle.

The current OpenMx repo also does not use lifecycle AFAICT. Is there a branch or ref that does?

**Comment by jpritikin** [comment]
Oh! Look [here](https://win-builder.r-project.org/incoming_pretest/OpenMx_2.17.0_20200213_225758/)

**Comment by gaborcsardi** [comment]
Yeah, so the problem is that you `.Rbuildignore` the `build` directory. `R CMD build` puts the PDF manual there, but then the whole directory is ignored so it'll not be in the built package.

**Comment by jpritikin** [comment]
Whoa! OpenMx uses the build directory as a temporary place to stash random build artifacts. I didn't realize that it would clash with R's package workflow. How about if I use a directory called `staging` instead of `build`? Will that solve it?

**Comment by gaborcsardi** [comment]
I guess so.

**Comment by jpritikin** [comment]
I'll try it. Thanks for your help!

**Comment by lionel-** [comment]
Thanks @gaborcsardi I would never have figured this out!

**Comment by StevenMMortimer** [comment]
@jpritikin  I'm having a similar issue. Hoping you or another expert on the thread might be able to provide some additional insight since there isn't much addressing the issue on StackOverflow or elsewhere. 

My CRAN submission passed somehow 🤷‍♂️  even though all of my GitHub Action (GHA) workflows show that same message since adding the lifecycle badges to my package
```
Package has help file(s) containing install/render-stage \Sexpr{} expressions but no prebuilt PDF manual.
```  
I removed `--no-manual` from `rcmdcheck(args = c(...))` in my GHA workflows and added `- uses: r-lib/actions/setup-tinytex@v1` so TinyTex in available to create the PDF (named "pkg-name.pdf"), but still the check still prints out the same message very early on in the process. I'm not sure how to silence the message or really what I could do to ensure that future CRAN submissions pass. Thanks so much for your time and ideas!

**Start of GitHub Action Log that runs R CMD check**
```sh
Run rcmdcheck::rcmdcheck(args = c("--as-cran"), error_on = "warning", check_dir = "check")
── R CMD build ─────────────────────────────────────────────────────────────────
* checking for file ‘.../DESCRIPTION’ ... OK
* preparing ‘salesforcer’:
* checking DESCRIPTION meta-information ... OK
* installing the package to process help pages
* creating vignettes ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘salesforcer_0.2.0.tar.gz’

── R CMD check ─────────────────────────────────────────────────────────────────
* using log directory ‘/Users/runner/work/salesforcer/salesforcer/check/salesforcer.Rcheck’
* using R version 4.0.2 (2020-06-22)
* using platform: x86_64-apple-darwin17.0 (64-bit)
* using session charset: UTF-8
* using option ‘--as-cran’
* checking for file ‘salesforcer/DESCRIPTION’ ... OK
* this is package ‘salesforcer’ version ‘0.2.0.9000’
* package encoding: UTF-8
* checking CRAN incoming feasibility ... NOTE
Maintainer: ‘Steven M. Mortimer <***>’

Package has help file(s) containing install/render-stage \Sexpr{} expressions but no prebuilt PDF manual.
* checking package namespace information ... OK
* checking package dependencies ... OK

... (log continues)
```

**Comment by lionel-** [comment]
Try using inline markdown to create the badges:

```r
#' `r lifecycle::badge("deprecated")`
```

This requires a recent roxygen. This is now the recommended way to insert a badge, though the documentation hasn't followed up yet.

**Comment by StevenMMortimer** [comment]
@lionel- Thanks for the quick reply! That works! 

It also fixes the error messages from {spelling} as noted in #19 and ropensci/spelling#42

Thanks again!
