### ISSUE TITLE
Cannot install lifecycle; inhibits installation of kableExtra

### ISSUE THREAD

**Issue by sigmasigmaiota** [r-lib/lifecycle#42]
any ideas on how to install and implement on R 3.6.3 on Windows 10?

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

> remotes::install_github("r-lib/lifecycle")
Downloading GitHub repo r-lib/lifecycle@master
Error: Failed to install 'lifecycle' from GitHub:
  System command 'Rcmd.exe' failed, exit status: -1, stdout + stderr empty

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

additionally, we have

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
> install.packages('lifecycle')

  There is a binary version available but the source version is later:
          binary source needs_compilation
lifecycle  0.1.0  0.2.0             FALSE

installing the source package ‘lifecycle’

trying URL 'https://cran.rstudio.com/src/contrib/lifecycle_0.2.0.tar.gz'
Content type 'application/x-gzip' length 164455 bytes (160 KB)
downloaded 160 KB

Warning in install.packages :
  installation of package ‘lifecycle’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\sjones\AppData\Local\Temp\RtmpiuiiLZ\downloaded_packages’

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
Thank you!

**Comment by sigmasigmaiota** [comment]
Remedied by downloading binary zip from CRAN and installing with repo = NULL.
Sorry for the false alarm!

**Comment by lionel-** [comment]
For future reference, you need to install Rtools to install packages from source on Windows.
