### ISSUE TITLE
"questioning" is a non-intuitive stage name.

### ISSUE THREAD

**Issue by bergsmat** [r-lib/lifecycle#45]
"questioning" is a non-intuitive stage name that genuinely confused me (native English speaker).  All the other stage names for both functions and [packages](https://www.tidyverse.org/lifecycle/) modify the software itself, whereas "questioning" is an action of the developer (an exception to parallel structure).   Just as "retired" was recently replaced with "superseded", I suggest replacing "questioning" with "questioned" or some equivalent adjective.

**Comment by lionel-** [comment]
Thanks for the feedback! I think at this point it would be too much trouble to rename the stage.
