### ISSUE TITLE
Support more than one alternative?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/lifecycle#46]
``` r
lifecycle::deprecate_soft("1.0.0", "as_tibble()", with = c("as_tibble_row()", "tibble()"))
#> Error in lifecycle_build_message(when, what, with, details, "deprecate_soft"): is_null(with) || is_string(with) is not TRUE
```

<sup>Created on 2020-03-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
I think this is a sufficiently specialised need that you can just use the `details` argument to hand craft the message.
