### ISSUE TITLE
Deprecating behaviours

### ISSUE THREAD

**Issue by lionel-** [r-lib/lifecycle#48]
Other than functions and arguments.

**Comment by hadley** [comment]
I think `details` has this covered.

**Comment by lionel-** [comment]
The warning message will either refer to a function or to an argument so I don't think `details` is sufficient here. We don't want to mislead the user into thinking a whole function is deprecated.

I was thinking we need something like `0` suffixed variants which take a raw message instead of a spec.

**Comment by hadley** [comment]
Do you have a specific case where we've deprecated something that isn't a function or argument?

**Comment by lionel-** [comment]
I don't remember exactly, I think it was some kind of global or contextual state. Deprecating a global option (or one its values) would be an example.

**Comment by lionel-** [comment]
This is now discussed in #120.
