### ISSUE TITLE
lifecycle and testthat when run via revdepcheck makes "lifecycle" suggestion toward the wrong package

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-lib/lifecycle#52]
Not sure where this should be reported, but I suspect it's related to the lifecycle packaage due to the following "lifecycle" suggestions, so I figured I report it here.

Below is the testthat output produced for SpaDES.core when running `revdepcheck::revdep_check()` on my future package.  The output makes suggestions toward my future package and not toward SpaDES.core.  That doesn't look right.

```r
$ cat revdep/checks/SpaDES.core/new/SpaDES.core.Rcheck/tests/test-all.Rout
...
> library(testthat)
> test_check("SpaDES.core")
Loading required package: SpaDES.core
Loading required package: quickPlot
Loading required package: reproducible
✔ Setting active project to '/wynton/home/cbi/hb/repositories/future'
● Copy and paste the following lines into '/wynton/home/cbi/hb/repositories/future/R/future-package.R':
  ## usethis namespace: start
  #' @importFrom lifecycle deprecate_soft
  ## usethis namespace: end
  NULL
✔ Copied SVG badges to 'man/figures/'
● Add badges in documentation topics by inserting one of:
  - \lifecycle{experimental}
  - \lifecycle{maturing}
  - \lifecycle{stable}
  - \lifecycle{superseded}
  - \lifecycle{questioning}
  - \lifecycle{soft-deprecated}
  - \lifecycle{deprecated}
  - \lifecycle{defunct}
  - \lifecycle{archived}

Attaching package: 'SpaDES.core'
```

This is with:
```r
> packageVersion("lifecycle")
[1] ‘0.2.0’
> packageVersion("testthat")                                                                                                        
[1] ‘2.3.2’
> packageVersion("revdepcheck")
[1] ‘1.0.0.9001’
```

**Comment by HenrikBengtsson** [comment]
Oh... and it also wrote files to my package's `man/` folder;

```sh
$ ls -lrt man/figures/
total 9
-rw-r--r--. 1 hb cbi 971 Jul  7 19:45 lifecycle-superseded.svg
-rw-r--r--. 1 hb cbi 956 Jul  7 19:45 lifecycle-stable.svg
-rw-r--r--. 1 hb cbi 982 Jul  7 19:45 lifecycle-soft-deprecated.svg
-rw-r--r--. 1 hb cbi 972 Jul  7 19:45 lifecycle-questioning.svg
-rw-r--r--. 1 hb cbi 966 Jul  7 19:45 lifecycle-maturing.svg
-rw-r--r--. 1 hb cbi 974 Jul  7 19:45 lifecycle-experimental.svg
-rw-r--r--. 1 hb cbi 970 Jul  7 19:45 lifecycle-deprecated.svg
-rw-r--r--. 1 hb cbi 964 Jul  7 19:45 lifecycle-defunct.svg
-rw-r--r--. 1 hb cbi 967 Jul  7 19:45 lifecycle-archived.svg
```

**Comment by HenrikBengtsson** [comment]
... and it updated my DESCRIPTION file too:
```diff
diff --git a/DESCRIPTION b/DESCRIPTION
index 27e44ea..5cd6988 100644
--- a/DESCRIPTION
+++ b/DESCRIPTION
@@ -6,7 +6,8 @@ Imports:
     globals (>= 0.12.5),
     listenv (>= 0.8.0),
     parallel,
-    utils
+    utils,
+    lifecycle
 Suggests:
     RhpcBLASctl,
     R.rsp,
@@ -37,3 +38,4 @@ URL: https://github.com/HenrikBengtsson/future
 BugReports: https://github.com/HenrikBengtsson/future/issues
 RoxygenNote: 7.1.1
 Roxygen: list(markdown = TRUE)
+RdMacros: lifecycle
```

**Comment by lionel-** [comment]
It looks like something is calling `usethis::use_lifecycle()`. From the tests or an onLoad/onAttach hook? It could be SpaDES.core, quickPlot, or reproducible?

`use_lifecycle()` is meant to be an interactive function for end users creating a package.

**Comment by lionel-** [comment]
I think this is: https://github.com/cran/reproducible/blob/4ba3d3b763c9a1b3109983bcbbd5c9e7ebdb7ce3/R/cache.R#L1689

**Comment by HenrikBengtsson** [comment]
Thanks for backtracing this.  However, even if there is a misuse of `usethis::use_lifecycle()`, that call shouldn't mess with upstream folders and files, correct?  Could it be that there's an "automatic" lookup of a package folder that fails here?  

Should this issue be transferred to https://github.com/r-lib/usethis/issues?

**Comment by lionel-** [comment]
usethis detects a package somewhere in the folder hierarchy, so it's working as intended. I have opened an issue in your reverse dependency repo: https://github.com/PredictiveEcology/reproducible/issues/147

**Comment by lionel-** [comment]
Though I wonder if usethis (or a subset of usethis functions) should refuse to work non-interactively? Would this make sense @jennybc

**Comment by jennybc** [comment]
> Though I wonder if usethis (or a subset of usethis functions) should refuse to work non-interactively? 

It's explicitly a workflow package, so that would basically be everything.

This looks like a really peculiar call to find in an R package:

https://github.com/cran/reproducible/blob/4ba3d3b763c9a1b3109983bcbbd5c9e7ebdb7ce3/R/cache.R#L1689

I think that's our root cause.

I've had at least one other weird revdep issue where someone mistakenly included an entire file of workflow commands in `R/`. However, I don't think usethis should really be responsible for guarding against these sort of events. It's true that every now and then this happens, just like `browser()` calls occasionally make it into CRAN packages. We discover it and the maintainer can fix.

**Comment by achubaty** [comment]
Apologies. That call was included in error, and we have removed the use of `lifecycle` in https://github.com/PredictiveEcology/reproducible/commit/728145cc8dd436a6a11965b999e5a443923a8976. This fix will be included in our next CRAN release.

**Comment by lionel-** [comment]
Thanks @achubaty!

**Comment by HenrikBengtsson** [comment]
Thxs all
