### ISSUE TITLE
A way to `lifecycle::deprecate_warn()` an R6 method

### ISSUE THREAD

**Issue by colearendt** [r-lib/lifecycle#54]
Deprecating an R6 method does not currently work because the "function" being deprecated does not _actually_ exist (but needs to be instantiated by initializing a class)

**Comment by hadley** [comment]
Minimal reprex:

``` r
A <- R6::R6Class("A", list(
  old_f = function() {
    lifecycle::deprecate_warn("1.0.0", "A$old_f()", "A$new_f()")
    self$new_f()
  },
  new_f = function() {
    "10"
  }
))
A$new()$old_f()
#> Error: Internal error: `what` must refer to a function name.
```

<sup>Created on 2021-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by kpagacz** [comment]
What about active bindings?

**Comment by hadley** [comment]
@kpagacz what about them? If there's a problem, please create a reprex and file a new issue.
