### ISSUE TITLE
Function badges don't play nice with RStudio Comment Reflow

### ISSUE THREAD

**Issue by mkirzon** [r-lib/lifecycle#61]
When I write up roxygen documentation, I like to use the RStudio "Reflow Comment" shortcut to word wrap comments at the default ruler position. I also put lifecycle badges at the top of the description section. What happens when I use both, is that the description text gets placed on the same line as the badge which doesn't render properly downstream. 

### Roxygen pre-reflow
```r
#' Some title
#'
#' \lifecycle{maturing}
#' This is the function description
```

### Roxygen after reflow
```r
#' Some title
#'
#' \lifecycle{maturing} This is the function description
```

**Comment by hadley** [comment]
I don't think there's anything that lifecycle can do about this, unfortunately. One hack is to add a blank line:

```
#' Some title
#'
#' \lifecycle{maturing}

#' This is the function description
```
