### ISSUE TITLE
last_warnings() doesn't take simplify argument

### ISSUE THREAD

**Issue by hadley** [r-lib/lifecycle#67]
Despite the documentation saying:

> If you call these in the console, these warnings are printed with a backtrace. Pass the simplify argument to control the verbosity of the backtrace. It supports one of "branch" (the default), "collapse", and "none" (in increasing order of verbosity).

**Comment by lionel-** [comment]
The documentation should mention that `print()` currently must be called explicitly:

```r
f <- function() deprecate_soft("1.0.0", "foo()")
g <- function() deprecate_soft("1.0.0", "bar()")

evalq({
  f()
  g()
})

print(last_warnings(), simplify = "none")
#> [[1]]
#> <deprecated>
#> message: `foo()` was deprecated in lifecycle 1.0.0.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_warnings()` to see where this warning was generated.
#> backtrace:
#>     █
#>  1. ├─base::evalq(...)
#>  2. │ └─base::evalq(...)
#>  3. └─global::f()
#>  4.   └─lifecycle::deprecate_soft("1.0.0", "foo()")
#>
#> [[2]]
#> <deprecated>
#> message: `bar()` was deprecated in lifecycle 1.0.0.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_warnings()` to see where this warning was generated.
#> backtrace:
#>     █
#>  1. ├─base::evalq(...)
#>  2. │ └─base::evalq(...)
#>  3. └─global::g()
#>  4.   └─lifecycle::deprecate_soft("1.0.0", "bar()")
```

Would you like to update the documentation to make that clearer, or should we take a `simplify` argument in `last_warnings()` and return a specially classed list that passes the parameters over?

**Comment by hadley** [comment]
Hmmm, it feels like if we did add an argument it should really be implemented somewhere in rlang, so I think just fixing the docs is fine here.
