### ISSUE TITLE
Reset warnings?

### ISSUE THREAD

**Issue by hadley** [r-lib/lifecycle#70]
Should we provide a function to reset the seen status of all warnings? Then we could say:

```R
`data_frame()` is deprecated as of tibble 1.1.0.
Please use `tibble()` instead.
This warning is displayed once every 8 hours. Use `lifecycle::reset()` to see again.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
```

**Comment by hadley** [comment]
If you don't think this function is a good idea, we should still include some advice on how to see the warning again.

**Comment by Moohan** [comment]
I came here looking for exactly this, I don't see a `lifecycle::reset()` function, nor could I find any instructions on how to reset warnings. Can anyone point me in the right direction?
