### ISSUE TITLE
Example demonstrating how to deprecate 2 arguments in the same function?

### ISSUE THREAD

**Issue by k-doering-NOAA** [r-lib/lifecycle#71]
I find the [example for the functions `deprecated` and `is_present`](https://lifecycle.r-lib.org/reference/deprecated.html) helpful for learning how to use these functions. However, I have been  struggling to apply them in a succinct way when deprecating multiple arguments in the same function. Is there an example of deprecating 2 or more arguments in the same function, using a for loop or apply statement to avoid writing multiple `if` statements and calls to `deprecate_warn` in the function?

Please let me know if it would be helpful to provide a more specific example!

**Comment by hadley** [comment]
I'd recommend just using multiple if statements.

**Comment by k-doering-NOAA** [comment]
Thanks @hadley, I will stick with the simple solution, then!
