### ISSUE TITLE
lifecycle::is_present throws error when dealing with quosures

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/lifecycle#92]
I want to change the name of an argument using `lifecycle::is_present`.

However, in my functon, the argument is normally used with quosures, so the example of [the doc](https://rdrr.io/cran/lifecycle/man/deprecated.html) does not work:

``` r
library(tidyverse)
library(lifecycle)
my_fun = function(df, cols, .vars = deprecated()){
  if (is_present(.vars)) {
    deprecate_warn("0.1.6", "my_fun(.vars=)", "my_fun(cols=)")
    cols <- .vars
  }
  select(df, {{cols}})
}

my_fun(iris, cols=Sepal.Length) %>% head()
#>   Sepal.Length
#> 1          5.1
#> 2          4.9
#> 3          4.7
#> 4          4.6
#> 5          5.0
#> 6          5.4
my_fun(iris, .vars=Sepal.Length) %>% head()
#> Error in is_reference(x, quote(expr = )): objet 'Sepal.Length' introuvable
```
<sup>Created on 2021-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I know that the line `cols <- .vars` will not work either, I'm still looking for a solution.

A workaround would be:

```r
library(rlang)
if (quo_is_missing(enquo(cols)) && !quo_is_missing(enquo(.vars))) {
  deprecate_warn("0.1.6", "my_fun(.vars=)", "my_fun(cols=)")
  cols <- .vars #outch
}

```

If this is out of the scope of this function, maybe it would still be worth specifying this case in the doc?

**Comment by hadley** [comment]
You'll have to just use `missing()` here because you can't actually evaluate the argument. I think this is sufficiently rare that it's not worth documenting, but if others stumble across it, I'll definitely reconsider.
